# Generated by Django 3.2.16 on 2022-11-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0015_alter_about_about_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='image',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='num',
        ),
        migrations.AddField(
            model_name='projects',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='example',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='link1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='link2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='link3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='link4',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='link5',
            field=models.URLField(blank=True, null=True),
        ),
    ]
